# 训练配置文件

# SRN训练配置
srn:
  # 骨干网络 (resnet101/resnet50/resnet34/resnet18)
  backbone: 'resnet101'
  # 是否使用预训练权重
  pretrained: true
  # 学习率
  learning_rate: 0.001
  # 批次大小
  batch_size: 16
  # 训练轮数
  epochs: 50
  # 特征维度 (需要与骨干网络匹配)
  feature_dims: [2048, 1024, 512]
  # Dropout率
  dropout_rate: 0.5
  # 设备配置 (cuda/cpu)
  device: 'cuda'
  # 学习率调度器配置
  scheduler:
    # 调整步长
    step_size: 10
    # 衰减因子
    gamma: 0.1

# 回归器训练配置
regressor:
  # 模型类型
  model_type: 'lightgbm'
  # 模型参数
  params:
    # 目标函数
    objective: 'regression'
    # 评估指标
    metric: 'mae'
    # 提升类型
    boosting_type: 'gbdt'
    # 叶子节点数
    num_leaves: 31
    # 学习率
    learning_rate: 0.05
    # 估计器数量
    n_estimators: 100

# 数据配置
data:
  # 数据目录
  data_dir: 'data'
  # 训练集列表文件
  train_list_file: 'data/metadata/train_list.csv'
  # 验证集列表文件
  val_list_file: 'data/metadata/val_list.csv'
  # 测试集列表文件
  test_list_file: 'data/metadata/test_list.csv'

# 模型保存配置
# 模型保存目录
model_save_dir: 'models'
# 模型保存间隔 (epoch)
save_interval: 10

# 其他配置
# 数据加载工作进程数
num_workers: 4
# 随机种子
random_seed: 42
